In [2]:
import numpy as np
import pprint
from Environment import GridworldEnv
from pprint import PrettyPrinter

%pprint
pp = PrettyPrinter(indent=4)

Pretty printing has been turned OFF
Pretty printing has been turned ON


In [32]:
env = GridworldEnv()
random_policy = np.ones([env.nS, env.nA])/env.nA
print(random_policy)

[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]]


In [41]:
def policy_eval(policy, environment, discount_factor=1.0, theta=1.0):
    env = environment # 环境变量
    
    # 初始化一个全0的价值函数
    V = np.zeros(env.nS)
    
    # 迭代开始
    for _ in range(10000):
        delta = 0
        
        # 对于GridWorld中的每一个状态都进行全备份
        for s in range(env.nS):
            v = 0
            # 检查下一个有可能执行的动作
            for a, action_prob in enumerate(policy[s]):
                
                # 对于每一个动作检查下一个状态
                for  prob, next_state, reward, done in env.P[s][a]:
                    # 累积计算下一个动作的期望价值
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
                    
            # 选出最大的变化量
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        
        print("="*60, _)
        print(V.reshape(env.shape))
        
        # 停止标志位
        if delta <= theta:
            break
    
    return np.array(V)

In [6]:
v = policy_eval(random_policy, env)
print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

============================================================ 0
[[-1.         -1.25       -1.3125     -1.328125  ]
 [-1.25       -1.         -1.578125   -1.        ]
 [-1.3125     -1.578125   -1.7890625  -1.        ]
 [-1.         -1.64453125 -1.85839844  1.        ]]
============================================================ 1
[[-2.125      -2.421875   -2.66015625 -2.57910156]
 [-2.421875   -2.         -2.86230469 -2.        ]
 [-2.578125   -3.00292969 -3.1809082  -2.        ]
 [-2.         -3.12646484 -2.79144287  2.        ]]
============================================================ 2
[[-3.2734375  -3.58886719 -3.92260742 -3.77020264]
 [-3.56835938 -3.         -4.02587891 -3.        ]
 [-3.78735352 -4.27368164 -4.27275085 -3.        ]
 [-3.         -4.29789734 -3.34052277  3.        ]]
============================================================ 3
[[-4.42602539 -4.734375   -5.11326599 -4.91341782]
 [-4.69543457 -4.         -5.09650421 -4.        ]
 [-4.93911743 -5.37744141 -5.20

In [21]:
def gen_random_policy():
    return np.random.choice(4, size=((16)))

n_policy = 100
policy_pop = [gen_random_policy() for _ in range(n_policy)]
pprint.pprint(policy_pop[:10])

[array([2, 1, 3, 1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 3, 2, 3]),
 array([0, 3, 1, 1, 0, 3, 3, 1, 2, 1, 0, 1, 2, 1, 2, 1]),
 array([2, 2, 2, 1, 2, 3, 1, 1, 1, 1, 1, 1, 2, 0, 3, 1]),
 array([3, 2, 0, 0, 2, 1, 1, 2, 0, 1, 3, 3, 0, 3, 0, 1]),
 array([1, 1, 1, 1, 1, 1, 3, 1, 0, 3, 1, 0, 0, 2, 3, 2]),
 array([0, 0, 0, 0, 0, 2, 3, 1, 1, 3, 2, 1, 3, 1, 0, 3]),
 array([2, 1, 3, 3, 2, 3, 2, 3, 2, 3, 3, 1, 0, 3, 0, 3]),
 array([2, 2, 2, 1, 3, 1, 0, 1, 3, 0, 2, 3, 3, 1, 0, 3]),
 array([0, 1, 2, 3, 0, 2, 2, 0, 0, 2, 2, 2, 3, 3, 1, 3]),
 array([3, 1, 2, 0, 0, 3, 0, 0, 3, 1, 3, 3, 0, 2, 1, 1])]


# Test the Spesfiy Input Policy

if I input a speciay policy what the value funciton calcuate by the policy evalutaiton.

In [9]:
input_policy = [2,1,2,3,2,0,2,0,1,2,2,0,0,1,1,0]

env = GridworldEnv()
policy = np.zeros([env.nS, env.nA])

for _, x in enumerate(input_policy):
    policy[_][x] = 1
    
print(policy)

[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]


In [7]:
def policy_eval(policy, environment, discount_factor=1.0, theta=0.1):
    env = environment # 环境变量
    
    # 初始化一个全0的价值函数
    V = np.zeros(env.nS)
    
    # 迭代开始
    for _ in range(50):
        delta = 0
        
        # 对于GridWorld中的每一个状态都进行全备份
        for s in range(env.nS):
            v = 0
            # 检查下一个有可能执行的动作
            for a, action_prob in enumerate(policy[s]):
                
                # 对于每一个动作检查下一个状态
                for  prob, next_state, reward, done in env.P[s][a]:
                    # 累积计算下一个动作的期望价值
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
                    
            # 选出最大的变化量
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        
        print("="*60, _)
        print(V.reshape(env.shape))
        
        # 停止标志位
        if delta <= theta:
            break
    
    return np.array(V)

In [8]:
v = policy_eval(policy, env)
print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

============================================================ 0
[[-1. -2. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  1.]]
============================================================ 1
[[-2. -3. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2.  0.  2.]]
============================================================ 2
[[-3. -4. -3. -3.]
 [-3. -3. -3. -3.]
 [-3. -3. -1. -3.]
 [-3. -1.  1.  3.]]
============================================================ 3
[[-4. -5. -4. -4.]
 [-4. -4. -2. -4.]
 [-4. -2.  0. -4.]
 [-4.  0.  2.  4.]]
============================================================ 4
[[-5. -6. -3. -5.]
 [-5. -5. -1. -5.]
 [-3. -1.  1. -5.]
 [-5.  1.  3.  5.]]
============================================================ 5
[[-6. -7. -2. -6.]
 [-4. -6.  0. -6.]
 [-2.  0.  2. -6.]
 [-6.  2.  4.  6.]]
============================================================ 6
[[-5. -6. -1. -7.]
 [-3. -7.  1. -7.]
 [-1.  1.  3. -7.]
 [-7.  3.  5.  7.]]
====================